#-------------------------------
# General Site Settings
title: CharlotteMaschke
logo: logo.svg # You can add own logo.
description: A website about my work on neuroscience and some art.


#-------------------------------
# Author Settings
blog:
  name: Charlotte Maschke
  image: me.png
  say-hello: <strong>Do you MIND?</strong>
  bio: Hi, I am Charlotte Maschke. I completed my PhD in the Integrated Program in Neuroscience at McGill University, 
    Canada working on identifying brain signatures of consciousness in unresponsive patients. 
    My PhD research focused on the development of a clinical tool to quantify capacity for consciousness following brain injury, 
    using anesthetic perturbation and brain dynamical properties. I is currently working as a Postdoctoral Fellow at Harvard Medical
     School and Aix-Marseille University, using whole-brain modelling for post-injuty treatment simulation. My work gravitates around the 
     concept of complex dynamics as a requirement for healthy brain function and the emergence of consciousness. Beyond my regular 
     research, I am  passionate about the intersection between science and art.
    
#-------------------------------
# Blog Settings
author:
  name: Charlotte Maschke
  image: me.png
  say-hello: <strong> Charlotte Maschke</strong>
  bio: I did my PhD in Neuroscience at McGill University and my work aims to prognosticate recovery of consciousness after traumatic brain injury.
    I am passionate about neuroscience of consciousness and the symbiosis of science and art.

#-------------------------------
# Contact links
github: https://github.com/CharlotteMaschke
email: /contact.html
